import type { TipoDocumento } from "@/types";

export const TIPOS_DOCUMENTO: TipoDocumento[] = [
  {
    id: "CC9",
    label: "CC-9 (Deuda)",
    nombre: "Comprobante de Causación",
    descripcion: "Registra el gasto y la deuda en el momento de recibir la cuenta.",
    requerido: true,
    color: "#10b981",
    minArchivos: 2,
    ayudaPareja: "la causación interna de Fundamiga y la factura/recibo de la empresa",
    categoria: "comprobantes",
  },
  {
    id: "DS",
    label: "DS (Soporte)",
    nombre: "Documento Soporte",
    descripcion: "Obligatorio para compras a proveedores informales (sin factura).",
    requerido: true,
    color: "#3b82f6",
    minArchivos: 2,
    ayudaPareja: "el documento soporte electrónico de la DIAN y la cuenta de cobro del proveedor",
    categoria: "comprobantes",
  },
  {
    id: "CC6",
    label: "CC-6 (Pago)",
    nombre: "Comprobante de Egreso",
    descripcion: "El recibo o soporte físico que demuestra que ya pagaste la deuda.",
    requerido: true,
    color: "#8b5cf6",
    minArchivos: 2,
    ayudaPareja: "el comprobante de egreso del sistema y el soporte de la transferencia bancaria",
    categoria: "comprobantes",
  },
  {
    id: "CC10",
    label: "CC-10 (Aprobación)",
    nombre: "Autorización de Pago",
    descripcion: "Firma o visto bueno interno para poder desembolsar el dinero.",
    requerido: true,
    color: "#f59e0b",
    minArchivos: 2,
    ayudaPareja: "la autorización de pago firmada y la cotización/solicitud de cobro soporte",
    categoria: "comprobantes",
  },
  {
    id: "FV",
    label: "FV (Factura)",
    nombre: "Factura de Venta",
    descripcion: "Factura legal electrónica. Si la subes, reemplaza al DS.",
    requerido: false,
    color: "#ec4899",
    categoria: "comprobantes",
  },
  {
    id: "BANC_CONCIL",
    label: "CONCILIACION",
    nombre: "Conciliación Bancaria",
    color: "#0d9488",
    minArchivos: 1,
    categoria: "bancos",
  },
  {
    id: "BANC_EXTRACT",
    label: "EXTRACTO",
    nombre: "Extracto Bancario",
    color: "#0d9488",
    minArchivos: 1,
    categoria: "bancos",
  },
  {
    id: "BANC_INFO",
    label: "INFORME TES.",
    nombre: "Informe de Tesorera (Bancos)",
    color: "#0d9488",
    minArchivos: 1,
    categoria: "bancos",
  },
  {
    id: "CAJA_CONCIL",
    label: "CONCILIACIONES",
    nombre: "Conciliación de Caja",
    color: "#65a30d",
    minArchivos: 1,
    categoria: "caja",
  },
  {
    id: "CAJA_INFO",
    label: "INFORME TES.",
    nombre: "Informe de Tesorera (Caja)",
    color: "#65a30d",
    minArchivos: 1,
    categoria: "caja",
  },
  {
    id: "CC11",
    label: "CC-11 (Capital)",
    nombre: "Capital Contable",
    descripcion: "Regulado por la NIF C-11, manejo del Patrimonio.",
    requerido: false,
    color: "#78350f",
    minArchivos: 1,
    categoria: "otros",
  },
  {
    id: "TD",
    label: "TD (Traslado)",
    nombre: "Traslado de Dinero",
    descripcion: "Movimientos internos de fondos entre cuentas o cajas.",
    requerido: false,
    color: "#475569",
    minArchivos: 1,
    categoria: "otros",
  },
  {
    id: "ING",
    label: "INGRESO",
    nombre: "Comprobante de Ingreso",
    descripcion: "Registro de entrada de dinero por cualquier concepto.",
    requerido: false,
    color: "#f97316",
    minArchivos: 1,
    categoria: "otros",
  },
  {
    id: "SS",
    label: "SS (Seg. Social)",
    nombre: "Seguridad Social",
    descripcion: "Pagos de salud, pensión y riesgos laborales.",
    requerido: false,
    color: "#4f46e5",
    minArchivos: 1,
    categoria: "otros",
  },
  {
    id: "CC1",
    label: "CC-1 (Banco)",
    nombre: "Extracto Bancario",
    descripcion: "Auxiliar contable o copia del movimiento de la cuenta de banco.",
    requerido: false,
    color: "#06b6d4",
    categoria: "otros",
  },
];

export const MESES = [
  "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio",
  "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre",
];

export const TIPOS_PAGO = [
  { value: "servicio",    label: "Servicio (internet, TV, etc.)" },
  { value: "nomina",      label: "Nómina / Honorarios" },
  { value: "arriendo",    label: "Arriendo" },
  { value: "suministros", label: "Suministros / Papelería" },
  { value: "otro",        label: "Otro" },
];
